machine:
  docker_layer_caching: true
  enabled: true
steps:
- checkout
- setup_node12
- install_python_requests
- run:
    command: mkdir -p /tmp/logs/test/integration/kind-olm-operator
    name: Create temporary directory for logs
- run:
    command: |
      export KUBERNETES_MONITOR_IMAGE_NAME_AND_TAG=$(./scripts/circleci-jobs/setup-integration-tests.py)
      .circleci/do-exclusively --branch staging --job ${CIRCLE_JOB} npm run test:integration:kindolm:operator
    name: Operator integration tests on plain k8s
- run:
    name: Delete Operator from Quay
    command: |
      ./scripts/operator/delete-operator-from-quay.sh
- run:
    command: |
      ./scripts/slack/notify_failure_on_branch.py "staging-integration-tests-operator-on-k8s-${CIRCLE_SHA1}"
    name: Notify Slack on failure
    when: on_fail
- store_artifacts:
    path: /tmp/logs/test/integration/kind-olm-operator
working_directory: ~/kubernetes-monitor
