sudo: false
dist: xenial
services: docker
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    on_failure: always
    on_success: never
    on_pull_requests: false
node_js:
  - '10'
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - npm install
jobs:
  include:
    # test stage
    - stage: Test
      if: type = pull_request
      script: npm run test
      name: Run kubernetes-monitor tests
    # release and deploy stage
    # TODO when we can build and publish a container
branches:
  only:
   - master
