description: Install requests library
steps:
  - run:
      name: Install Helm
      command: |
        export DEBIAN_FRONTEND=noninteractive
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install -y apt-transport-https
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update -qq
        sudo apt-get install -y helm
