version: 2

default_machine_config: &default_machine_config
  machine:
    enabled: true
    docker_layer_caching: true
  working_directory: ~/kubernetes-monitor

default_container_config: &default_container_config
  docker:
    - image: circleci/node:10
  working_directory: ~/kubernetes-monitor

staging_branch_only_filter: &staging_branch_only_filter
  filters:
    branches:
      only:
        - staging

main_branches_filter: &main_branches_filter
  filters:
    branches:
      ignore:
        - staging
        - master

jobs:
######################## PACKAGE MANAGER REGRESSION TESTS ########################
  package_manager_test_apk:
    <<: *default_machine_config
    steps:
      - checkout
      - run:
          name: APK Test
          command: |
            export NVM_DIR="/opt/circleci/.nvm" &&
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" &&
            nvm install v10 &&
            npm install &&
            npm run test:apk
      - run:
          name: Notify Slack on failure
          command: ./scripts/slack-notify-failure.sh "apk-tests"
          when: on_fail

  package_manager_test_apt:
    <<: *default_machine_config
    steps:
      - checkout
      - run:
          name: APT Test
          command: |
            export NVM_DIR="/opt/circleci/.nvm" &&
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" &&
            nvm install v10 &&
            npm install &&
            npm run test:apt
      - run:
          name: Notify Slack on failure
          command: ./scripts/slack-notify-failure.sh "apt-tests"
          when: on_fail
  package_manager_test_rpm:
    <<: *default_machine_config
    steps:
      - checkout
      - run:
          name: RPM Test
          command: |
            export NVM_DIR="/opt/circleci/.nvm" &&
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" &&
            nvm install v10 &&
            npm install &&
            npm run test:rpm
      - run:
          name: Notify Slack on failure
          command: ./scripts/slack-notify-failure.sh "rpm-tests"
          when: on_fail

######################## PR TO STAGING ########################
  test_discardable:
    <<: *default_machine_config
    steps:
      - checkout
      - run:
          name: TEST DISCARDABLE
          command: |
            export NVM_DIR="/opt/circleci/.nvm" &&
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" &&
            nvm install v10 &&
            npm install &&
            npm test

######################## MERGE TO STAGING ########################
  test_and_build:
    <<: *default_machine_config
    steps:
      - checkout
      - run:
          name: TEST AND BUILD
          command: |
            export NVM_DIR="/opt/circleci/.nvm" &&
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" &&
            nvm install v10 &&
            npm install &&
            npm run lint &&
            npm run build &&
            npm run test:unit &&
            docker login --username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASSWORD} &&
            IMAGE_NAME_CANDIDATE=snyk/kubernetes-monitor:staging-candidate-${CIRCLE_SHA1} &&
            ./scripts/build-image.sh ${IMAGE_NAME_CANDIDATE} &&
            docker push ${IMAGE_NAME_CANDIDATE} &&
            ./scripts/slack-notify-push.sh ${IMAGE_NAME_CANDIDATE} &&
            KUBERNETES_MONITOR_IMAGE_NAME_AND_TAG=${IMAGE_NAME_CANDIDATE} npm run test:integration
      - run:
          name: Notify Slack on failure
          command: ./scripts/slack-notify-failure.sh "staging-test"
          when: on_fail
  tag_and_push:
    <<: *default_container_config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: TAG AND PUSH
          command: |
            npm install &&
            docker login --username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASSWORD} &&
            unset CIRCLE_PULL_REQUEST &&
            unset CI_PULL_REQUEST &&
            unset CI_PULL_REQUESTS &&
            unset CIRCLE_PULL_REQUESTS &&
            npx semantic-release &&
            NEW_VERSION=`cat ./package.json | jq -r '.version'` &&
            ./scripts/approve-image.sh $NEW_VERSION
      - run:
          name: Notify Slack on failure
          command: ./scripts/slack-notify-failure.sh "staging-release"
          when: on_fail
  deploy_dev:
    <<: *default_container_config
    steps:
      - checkout
      - run:
          name: DEPLOY DEV
          command: |
            LATEST_TAG_WITH_V=`git describe --abbrev=0 --tags ${CIRCLE_SHA1}` &&
            LATEST_TAG=${LATEST_TAG_WITH_V:1}-approved &&
            ./scripts/slack-notify-deploy.sh $LATEST_TAG dev &&
            curl -i -H "Accept: application/json" -H "Content-Type: application/json" \
                -X POST -d "{\"docker_sha\":\"${LATEST_TAG}\", \
                              \"commit_hash\":\"${CIRCLE_SHA1}\"}" \
                https://my.dev.snyk.io/${DEV_DEPLOY_TOKEN}
      - run:
          name: Notify Slack on failure
          command: ./scripts/slack-notify-failure.sh "deploy-dev"
          when: on_fail

######################## PR TO MASTER ########################
  prepublish:
    <<: *default_container_config
    steps:
      - checkout
      - run:
          name: PREPUBLISH
          command: |
            ./scripts/slack-notify-pr.sh

######################## MERGE TO MASTER ########################
  publish:
    <<: *default_container_config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: PUBLISH
          command: |
            LATEST_TAG_WITH_V=`git describe --abbrev=0 --tags ${CIRCLE_SHA1}` &&
            LATEST_TAG=${LATEST_TAG_WITH_V:1} &&
            IMAGE_NAME_APPROVED=snyk/kubernetes-monitor:${LATEST_TAG}-approved &&
            IMAGE_NAME_PUBLISHED=snyk/kubernetes-monitor:${LATEST_TAG} &&
            docker login --username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASSWORD} &&
            docker pull ${IMAGE_NAME_APPROVED} &&
            docker tag ${IMAGE_NAME_APPROVED} ${IMAGE_NAME_PUBLISHED} &&
            docker push ${IMAGE_NAME_PUBLISHED} &&
            ./scripts/slack-notify-push.sh ${IMAGE_NAME_PUBLISHED} &&
            ./scripts/publish-gh-pages.sh ${LATEST_TAG}
      - run:
          name: Notify Slack on failure
          command: ./scripts/slack-notify-failure.sh "master"
          when: on_fail

  deploy_prod:
    <<: *default_container_config
    steps:
      - checkout
      - run:
          name: DEPLOY PROD
          command: |
            LATEST_TAG_WITH_V=`git describe --abbrev=0 --tags ${CIRCLE_SHA1}` &&
            LATEST_TAG=${LATEST_TAG_WITH_V:1} &&
            ./scripts/slack-notify-deploy.sh $LATEST_TAG prod &&
            curl -i -H "Accept: application/json" -H "Content-Type: application/json" \
                -X POST -d "{}" \
                https://my.prod.snyk.io/${PROD_DEPLOY_TOKEN}
      - run:
          name: Notify Slack on failure
          command: ./scripts/slack-notify-failure.sh "deploy-prod"
          when: on_fail

#######################################################################

workflows:
  version: 2
  PR_TO_STAGING:
    jobs:
      - test_discardable:
          <<: *main_branches_filter
      - package_manager_test_apk:
          <<: *main_branches_filter
      - package_manager_test_apt:
          <<: *main_branches_filter
      - package_manager_test_rpm:
          <<: *main_branches_filter

  MERGE_TO_STAGING:
    jobs:
      - test_and_build:
          <<: *staging_branch_only_filter
      - package_manager_test_apk:
          <<: *staging_branch_only_filter
      - package_manager_test_apt:
          <<: *staging_branch_only_filter
      - package_manager_test_rpm:
          <<: *staging_branch_only_filter
      - tag_and_push:
          requires:
            - test_and_build
            - package_manager_test_apk
            - package_manager_test_apt
            - package_manager_test_rpm
          <<: *staging_branch_only_filter
      - deploy_dev:
          requires:
            - tag_and_push
          <<: *staging_branch_only_filter

  MERGE_TO_MASTER:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master
      - deploy_prod:
          requires:
            - publish
          filters:
            branches:
              only:
                - master

general:
  branches:
    ignore:
      - gh-pages
